### ISSUE TITLE
hexpm/elixir:1.13.1-erlang-24.2-alpine-3.14.3 image is missing

### ISSUE THREAD

**Issue by hoyon** [hexpm/bob#105]
#103 bumped the 3.14.x alpine version to 3.14.3 but this image doesn't seem to be built.

I can see 1.13.1-erlang-23.3.4.10-alpine-3.14.3 and 1.13.1-erlang-24.2-alpine-3.14.2 on dockerhub but not 1.13.1-erlang-24.2-alpine-3.14.3.

It seems there are no images for alpine 3.14.3 with erlang 24.x for any elixir version.

**Comment by ericmj** [comment]
We don't rebuild for Alpine 3.14.3 if we already have a build for 3.14.2, otherwise we have to rebuild all OTP and Elixir versions for every patch version bump.

**Comment by hoyon** [comment]
Cool that make sense. Thanks for the quick response!

I'll have to look into manually building the image we need.
