### ISSUE TITLE
hexpm/elixir Ubuntu/Debian images don't support ICMP protocol while Alpine ones do

### ISSUE THREAD

**Issue by balena** [hexpm/bob#106]
The test consists in performing the following commands:

```bash
$ docker run --rm -ti hexpm/elixir:1.13.2-erlang-24.2.1-ubuntu-focal-20211006 sh
# iex
Erlang/OTP 24 [erts-12.2.1] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:1]

Interactive Elixir (1.13.2) - press Ctrl+C to exit (type h() ENTER for help)
iex(1)> :socket.open(:inet, :raw, :icmp)
{:error, {:invalid, {:protocol, :icmp}}}
```
and repeating for each Debian/Ubuntu images available.

Then if you perform the same for Alpine Linux, it actually works:
```bash
$ docker run --rm -ti hexpm/elixir-arm64:1.13.2-erlang-24.2.1-alpine-3.15.0 sh
/ # iex
Erlang/OTP 24 [erts-12.2.1] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:1]

Interactive Elixir (1.13.2) - press Ctrl+C to exit (type h() ENTER for help)
iex(1)> :socket.open(:inet, :raw, :icmp)
{:ok, {:"$socket", #Reference<0.4054872251.4063100932.145697>}}
```

The problem seems to be related to some missing package at build time. Reference seems to be here: https://github.com/erlang/otp/blob/aa7f201ac2405ef6bf25d3111934f89dc3e23b73/erts/emulator/nifs/common/socket_nif.c#L169. The definition `HAVE_LINUX_ERRQUEUE_H` seems to be missing during build time.

**Comment by josevalim** [comment]
Do you know which package is missing? If so, could you please send a PR?

**Comment by lbellomo** [comment]
I did some research and aschiavon91 is right in the previous comment: the `netbase` dependency is missing in the final erlang img.
For example to test it on several images:
```
# debian-bookworm
$ docker run -i -a stdout hexpm/elixir:1.15.8-erlang-25.3.2.9-debian-bookworm-20240904 sh -c 'echo ":socket.open(:inet, :raw, :icmp)" | iex'
iex(1)> {:error, {:invalid, {:protocol, :icmp}}}

# debian-bookworm with 'netbase'
$ docker run -i -a stdout hexpm/elixir:1.15.8-erlang-25.3.2.9-debian-bookworm-20240904 sh -c 'apt update && apt install netbase && echo ":socket.open(:inet, :raw, :icmp)" | iex'
Get:1 http://deb.debian.org/debian bookworm InRelease [151 kB]
[...]
iex(1)> {:ok, {:"$socket", #Reference<0.3787441770.2561802246.469>}}
```

I also test it for the following img (trying to grab one of each type) and it works on all of them when the package is installed:
- `hexpm/elixir:1.17.2-erlang-25.1.2.1-debian-bullseye-20240904`
- `hexpm/elixir:1.17.2-erlang-25.1.2.1-debian-bullseye-20240904-slim`
- `hexpm/elixir:1.14.5-erlang-25.2.3-debian-bullseye-20240904`
- `hexpm/elixir:1.12.3-erlang-22.1.8.1-debian-buster-20240612`
- `hexpm/elixir:1.17.1-erlang-26.1.2-ubuntu-focal-20240530`
- `hexpm/elixir:1.17.1-erlang-26.2.5.1-ubuntu-jammy-20240530`
- `hexpm/elixir:1.17.0-erlang-25.1.2.1-ubuntu-noble-20240605`

I did not test it for `arm64` and I have doubts [here](https://github.com/hexpm/bob/blob/main/priv/scripts/docker/erlang-ubuntu-noble.dockerfile#L50). It should work, but it would be good to confirm it.

**Comment by lbellomo** [comment]
I was able to test the images for the `arm64` architecture. It also works when installing the `netbase` package.
Now I do a PR to add the `netbase` package to the final step of the erlang dockerfiles.

**Comment by ericmj** [comment]
Closing in favor of PR.
