### ISSUE TITLE
OTP 25.0-rc2 for Elixir 1.13.4

### ISSUE THREAD

**Issue by dvic** [hexpm/bob#108]
Should we build OTP 25.0-rc2 for Elixir >= 1.13.4?

The release page it should work ;) https://github.com/elixir-lang/elixir/releases/tag/v1.13.4

**Comment by ericmj** [comment]
Traditionally we have not built Elixir against RC builds because building against an unstable version means that we cannot build Elixir 1.13.4 against the stable version when it is released.

**Comment by dvic** [comment]
> because building against an unstable version means that we cannot build Elixir 1.13.4 against the stable version when it is released.

I'm not sure I understand that last part, why exactly is this the case?

For now I'm fine on waiting by the way, just curious :)

**Comment by ericmj** [comment]
We do one build per major OTP version, if replace the existing build with a new one when 25.0 is released we will possibly be breaking things for users on 25.0-rc2.
