### ISSUE TITLE
Include hex + rebar in Elixir Docker Images?

### ISSUE THREAD

**Issue by aj-foster** [hexpm/bob#109]
Hello there 👋🏼 

I use Bob-built docker images for CI tasks across a number of projects, and it's a great resource you've provided for the community. Thanks for maintaining this.

Apologies if this has been discussed before (couldn't find any such discussion immediately via search): would you consider pre-installing hex and rebar in the Elixir docker images? Although there are many "nice-to-have" things that someone **could** put into these images for various use-cases, `mix local.hex --force` and `mix local.rebar --force` are two commands that are fairly universal in my experience.

Of course, there may be reasons why this isn't possible or desirable, which I'd be happy to learn about.

Thank you!

**Comment by ericmj** [comment]
The reason is that we don't want to rebuild images or add new images when new hex and rebar versions are released.
