### ISSUE TITLE
Not all ubuntu images were rebuilt for 25.0.1

### ISSUE THREAD

**Issue by princemaple** [hexpm/bob#116]
Looks like only jammy got rebuilt for 25.0.1

All others are still on 25.0.0 which has ssl issues.

![image](https://user-images.githubusercontent.com/1329716/174711168-498d4daa-4e44-446a-810e-bb2986e8d2c4.png)

**Comment by ericmj** [comment]
We don't rebuild images because then you don't know which specific version you are getting. You need to pull the 25.0.1 tag explicitly, for example `1.13.4-erlang-25.0.1-ubuntu-jammy-20220428`.
