### ISSUE TITLE
Latest erlang 25.0.3 builds not found on docker hub

### ISSUE THREAD

**Issue by benoawfu** [hexpm/bob#119]
[Erlang 25.0.3](https://github.com/erlang/otp/releases/tag/OTP-25.0.3) was released 4 days ago, but I can't find the builds for it on docker hub:
- [Erlang builds](https://hub.docker.com/r/hexpm/erlang/tags?page=1&name=25.0.3)
- [Elixir builds](https://hub.docker.com/r/hexpm/elixir/tags?page=1&name=25.0.3)

Is Bob on annual leave?

**Comment by maennchen** [comment]
Build seems to exist now.

**Comment by maennchen** [comment]
@benoawfu I see it in https://repo.hex.pm/builds/otp/ubuntu-20.04/builds.txt

**Comment by benoawfu** [comment]
The docker images with `25.0.3` look available on dockerhub since this morning.
Keeping this ticket as there might be an issue with the worker.

**Comment by ericmj** [comment]
Fixed now.
