### ISSUE TITLE
Alpine 3.16.1 Docker images missing

### ISSUE THREAD

**Issue by Odaeus** [hexpm/bob#123]
Hi,

I noticed that images for the latest Alpine Linux 3.16.1 (which contains a couple of CVE fixes [among other things](https://alpinelinux.org/posts/Alpine-3.16.1-released.html)) are [not present on Docker Hub](https://hub.docker.com/r/hexpm/elixir/tags?page=1&name=alpine-3.16.1) despite [being added 9 days previously](https://github.com/hexpm/bob/commit/1bd0c08fd54861d23b7b7b7d13d212fba236e226). The latest in the list is 3.16.0. Just wanted to check if something is broken here?

Thanks for providing this service!

**Comment by ericmj** [comment]
There has been no elixir or erlang release during that time so no new images have been built. We don't trigger build for patch releases of Alpine because that would require a lot more builds, only major or minor version bumps will trigger new builds.

Can you not get the new CVE versions by running `apk update/ugprade`?

**Comment by Odaeus** [comment]
Thanks for the reply and explanation! Having a specific label is always better when possible because update commands only get run if we reset the Docker cache, which isn't always easy to do in automated build environments. No worries though, we'll find a workaround if we need to really keep up-to-date.

**Comment by ericmj** [comment]
If this becomes a recurring problem we will reconsider forcing new builds for Alpine patch versions. Thanks for raising the issue.

**Comment by cnkk** [comment]
Hey @ericmj, same problem as in #137 and here again.
Alpine 3.17.2 is missing (was merged in PR https://github.com/hexpm/bob/pull/145)

**Comment by ericmj** [comment]
What tags are missing?

**Comment by ericmj** [comment]
We only build new OS patch versions when new releases of Elixir or Erlang are published.

**Comment by cnkk** [comment]
E.g. `1.14.3-erlang-25.2.3-alpine-3.17.2`


>We only build new OS patch versions when new releases of Elixir or Erlang are published.

Ah 💡

**Comment by jalhead** [comment]
Hi @ericmj - same problem (OS patch version for Alpine 3.17.3) - PR raised [#151](https://github.com/hexpm/bob/pull/151)
