### ISSUE TITLE
Missing tag for Alpine 3.16.3 and 3.17.0

### ISSUE THREAD

**Issue by krns** [hexpm/bob#137]
Hi,

I wanted to give OpenSSL 3 a try but noticed that Docker Hub is missing tags for Alpine 3.16.3 and 3.17.0. Although the support for Alpine 3.16.3 and 3.17.0 was added in https://github.com/hexpm/bob/pull/135 and https://github.com/hexpm/bob/pull/136

**Comment by krns** [comment]
Just found hat only minor updates will trigger a new build: https://github.com/hexpm/bob/issues/123#issuecomment-1218055611

So there is only missing the Alpine 3.17.0 tag :-)

**Comment by ericmj** [comment]
Builds for 3.17.0 is starting now.

**Comment by krns** [comment]
Thank you, Eric. Alpine 3.17.0 is already up and running :-)
