### ISSUE TITLE
debian-bullseye-20221004 permission issue

### ISSUE THREAD

**Issue by oliver-kriska** [hexpm/bob#138]
Hello,
we did upgrade with latest erlang to this docker image`hexpm/elixir:1.13.4-erlang-25.2-debian-bullseye-20221004-slim` and we get this permission issue on Github Action when we try to build docker image:
```
error checking context: no permission to read from '/home/runner/work/platform/platform/deps/socket/README.md'
Error: Process completed with exit code 1.
```
It's Phoenix app with regular docker image build. I tried to replicate that issue locally but it works. When I did downgrade back to 
`hexpm/elixir:1.13.4-erlang-25.1-debian-bullseye-20220801-slim` it works too. So I'm not sure how to debug it because GH Actions debugging is very limited. 

Hex package socket is in version `0.3.13` based on our `mix.lock`. Any suggestion where problem can be?

**Comment by ericmj** [comment]
Sorry, I don't know what the issue could be. Nothing changed on our end between the builds of those versions.
