### ISSUE TITLE
Latest Docker images not build for `amd64`

### ISSUE THREAD

**Issue by timothyvanderaerden** [hexpm/bob#164]
It seems that the latest Docker images where not build for `amd64`,  the last package build for `amd64` seems to be `1.13.4-erlang-23.3.4.9-ubuntu-bionic-20230126`.

**Comment by benoawfu** [comment]
There are amd64 images on that repo: [`hexpm/elixir-amd64`](https://hub.docker.com/r/hexpm/elixir-amd64), though slightly less up to date (does not contain OTP 25.3.2.1 as of now).

**Comment by ericmj** [comment]
Should be built now
