### ISSUE TITLE
Erlang not built for Ubuntu since 2023-06-08

### ISSUE THREAD

**Issue by michallepicki** [hexpm/bob#168]
I was looking to install OTP 26.0.1 but this version doesn't seem to be available:
https://repo.hex.pm/builds/otp/ubuntu-20.04/builds.txt
https://repo.hex.pm/builds/otp/ubuntu-22.04/builds.txt

**Comment by cgrothaus** [comment]
This is also true for the new domain builds.hex.pm, i.e. https://builds.hex.pm/builds/otp/ubuntu-22.04/builds.txt does not contain OTP 26.0.1 either. This is a caching problem, if I add an arbitrary query param to the URL I get fresh contents: https://builds.hex.pm/builds/otp/ubuntu-22.04/builds.txt?nocache.

This may be related to #159. 

FYI @ericmj .

**Comment by ericmj** [comment]
Thanks for the report, fixed in https://github.com/hexpm/bob/commit/8968ebc4189b2154305d5ab07f237b2728443475.
