### ISSUE TITLE
Bad zipfile error

### ISSUE THREAD

**Issue by duff** [hexpm/bob#18]
Hi there,

I'm not sure if this is an issue for `bob` or for https://github.com/asdf-vm/asdf-elixir. I was hoping someone might be willing to point me in the right direction so that I could possibly offer a PR.

When I run `asdf install elixir 1.7.0`, that works... but it looks like it's compiled against OTP 19:

```
Erlang/OTP 21 [erts-10.0] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [hipe]

Elixir 1.7.0 (compiled with Erlang/OTP 19)
```

According to [this commit](https://github.com/hexpm/bob/commit/1c5df09f4f26444af9e3e8153e05b859e86d8917) I'm thinking that may not be right?

I tried specifying the otp version like so:

```
✦  asdf install elixir 1.7.0-otp-21
/var/folders/7q/zx_b307j1hv9pxvmx37c1p8h0000gn/T//elixir-precompiled-1.7.0-otp-21.zip
** Resuming transfer from byte position 5126599
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
file #1:  bad zipfile offset (local header sig):  0
```

but I'm getting that bad zipfile error which led me to think that it may be an issue with `bob`?

Running `asdf install elixir 1.6.5-otp-21` works great by the way.  Curiously, `asdf install elixir 1.6.6-otp-21` has the bad zipfile too.

I thought I'd try compiling from source using `asdf install elixir ref:v1.7.0`. That looks like it's working perfectly:

```
✦  elixir --version
Erlang/OTP 21 [erts-10.0] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [hipe]

Elixir 1.7.0 (compiled with Erlang/OTP 21)
```

All in all, I was thinking that it would be great to be able to specify the otp version and not get the bad zipfile and I was thinking that `asdf install elixir 1.7.0` should potentially use otp-20.

Thanks so much!

**Comment by ericmj** [comment]
I'm not sure what is happening. Everything is working for me:

```
> asdf install elixir 1.7.0
/var/folders/0w/tj_clcfd1blfmh0xg6jjl1q80000gq/T//elixir-precompiled-1.7.0.zip

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 5011k  100 5011k    0     0  3590k      0  0:00:01  0:00:01 --:--:-- 3589k
> asdf local elixir 1.7.0
> elixir -v
Erlang/OTP 21 [erts-10.0] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:1] [hipe]

Elixir 1.7.0 (compiled with Erlang/OTP 20)
```

```
> asdf install elixir 1.7.0-otp-21

/var/folders/0w/tj_clcfd1blfmh0xg6jjl1q80000gq/T//elixir-precompiled-1.7.0-otp-21.zip
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 5006k  100 5006k    0     0  4136k      0  0:00:01  0:00:01 --:--:-- 4137k
```

**Comment by wojtekmach** [comment]
> ** Resuming transfer from byte position 5126599
>  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
>                                 Dload  Upload   Total   Spent    Left  Speed
>  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
> file #1:  bad zipfile offset (local header sig):  0

I suspect there's a problem with resuming transfer.

**Comment by duff** [comment]
I googled a bunch for that bad zipfile offset error, but didn't find anything overly promising. The strange part is that all normal straight up versions all work for me. And _some_ `-otp-X` versions work too. But a number of `-otp-X` versions trigger the bad zipfile offset error for me.

And I've tried many times, noting that the same versions always cause the same results. This leads me to think that it's not a connectivity issue and it's not a timing thing, but rather that there may be a difference between the zipfiles. Is that possible?

Working versions for me:

```
All regular versions (like 1.7.0)
1.6.1-otp-20
1.6.3-otp-20
1.6.3-otp-21
1.6.4-otp-19
1.6.4-otp-20
1.6.5-otp-20
1.6.5-otp-21
```

Failing versions for me:

```
1.7.0-otp-21
1.7.0-otp-20
1.6.6-otp-21
1.6.6-otp-20
```

Now that I'm listing them out, it looks like maybe there's a difference between `1.6.6/1.7.0` and previous versions? I know this seems odd, but I thought I'd report it in case others may be experiencing the same issue and in case anyone might have ideas as to what might be different.

Thank you @ericmj and @wojtekmach!

**Comment by ericmj** [comment]
There should be no zipfile changes because the build process hasn't changed. Try reinstalling asdf and cleaning out the directories it uses.

This seems to be an issue with asdf resuming transfers. Can you show a case that fails without `Resuming transfer from byte position`?

**Comment by duff** [comment]
I just tried again and now all of those versions that were failing to install are installing perfectly. I'm so confused as to why it's working now! I was about to try your suggestion to re-install asdf and thought I'd give it one more try before doing so.

I'm so sorry to have wasted y'all's time! Given how consistent some versions were failing, I was so sure that it wasn't a personal issue. And now that everything is working, I'm forced to conclude that there's clearly not a systemic concern. Thanks so much for your help. 

Shamefully closing this issue. 😊

**Comment by wojtekmach** [comment]
no worries, glad all is well now!
