### ISSUE TITLE
`arm64` images?

### ISSUE THREAD

**Issue by halostatue** [hexpm/bob#181]
I don't need this right away, but these images are only available for the amd64 architecture, precluding their use on AWS Graviton processors or even for clean testing on modern macOS.

Would there be interest in adding arm64 image support; I could investigate a PR for it sometime in December.

**Comment by wojtekmach** [comment]
You may want to check out https://beammachine.cloud/. One obvious improvement is to have a CDN in front so if that sounds interesting consider discussing that with maintainers.

id personally love to see this folded into Hex but we don’t have cycles to do so at the moment and so I’ll close but feel free to continue discussing.

**Comment by ericmj** [comment]
If you are referring to docker images we do build them for arm64.

If you are referring to the erlang builds provided at https://builds.hex.pm/builds/otp/ubuntu-22.04/master.tar.gz then we would be willing to support arm64 if someone contributes the code.
