### ISSUE TITLE
Support for Amazon Public Elastic Container Registry

### ISSUE THREAD

**Issue by MrYawe** [hexpm/bob#184]
When using AWS, we often hit the DockerHub rate limit as [described here](https://www.learnaws.org/2022/11/21/aws-codebuild-docker-rate-limiting/).

The workaround that works for us is to pull images from the Amazon public registry instead of DockerHub.
So it requires us to upload each DockerHub images we want to use to the Amazon public registry. Here is an example for the [hexpm/elixir image](https://gallery.ecr.aws/tryriot/hexpm/elixir).

The best long-term solution would be to publish every hexpm Docker images to the [Amazon Public Elastic Container Registry](https://docs.aws.amazon.com/AmazonECR/latest/public/what-is-ecr.html) automatically under an hexpm account.

<img width="1469" alt="image" src="https://github.com/hexpm/bob/assets/8686039/b84d78ae-80c7-4815-8084-37a9d08bc6d5">

**Comment by ericmj** [comment]
I don't think it's feasible for Bob to also upload images to the various cloud container registries. We already have to pay for docker hub and I don't think we can motivate paying for more container registries.

I think the solution for you is to either authenticate to docker hub or continue copying images like you already do.

If someone wants to build a tool that copies the hexpm images from docker hub to other container registries they are very welcome to do that but Hex does unfortunately not have the resources to build it and pay for it.

**Comment by ericmj** [comment]
I am closing this issue but feel free to continue the discussion if you have ideas on how to solve the problem.
