### ISSUE TITLE
Missing ssh module

### ISSUE THREAD

**Issue by mattmatters** [hexpm/bob#194]
Hey folks!

I may be doing something completely wrong, but scratching my head over why the ssh module would be missing from Erlang. It looks like everything with ssl is being compiled with erlang. I even went and installed the openssh client in case that was what was missing. But sadly no luck!

I could definitely compile Erlang myself to fix the problem but it would definitely make our lives easier if it was bundled into this build.

**Comment by wojtekmach** [comment]
Could you describe step by step how did you install Erlang?

**Comment by mattmatters** [comment]
🤦 I'm a fool, this is why I shouldn't make issues late at night. I didn't start the `ssh` application 😅 . Thanks for responding so quickly and maintaining such a useful service.

**Comment by wojtekmach** [comment]
No worries, glad it's all good now!
