### ISSUE TITLE
checksum of existing file was changed

### ISSUE THREAD

**Issue by chulkilee** [hexpm/bob#20]
Related: #16 

My Dockerfile fetches precompiled elixir from bob, and checks the checksum to verify it's expected file.

```
RUN set -xe \
    && apk add --no-cache curl unzip \
    && curl -fSL -o elixir-precompiled.zip https://repo.hex.pm/builds/elixir/v1.7.1-otp-21.zip \
    && echo "c0954712e8969efff79ccf47a0847f9e336abca786cc145ffa9030cc6ed6055d  elixir-precompiled.zip" | sha256sum -c - \
    && unzip -d /usr/local elixir-precompiled.zip \
    && rm elixir-precompiled.zip \
    && apk del curl unzip \
    && mix local.hex --force \
    && mix local.rebar --force
```

It works well.. until the sha256 checksum of the file is changed - now it's `aa768d5e9ece02939f76be6a212c617500c1e84af23ba27fc1c10491ce7a2c5d`

Is it on purpose? For example, will it be changed when new elixir is released?

**Comment by ericmj** [comment]
This is not exactly on purpose but you cannot rely on the checksum because we may rebuild at any time and the builds are not reproducible.
