### ISSUE TITLE
Publish on ghcr.io?

### ISSUE THREAD

**Issue by halostatue** [hexpm/bob#200]
In #185, @ericmj [said](https://github.com/hexpm/bob/issues/185#issuecomment-2075281756_):
> Unfortunately not, Docker Hub is the authority of what images are available.

Since this is open source for open source projects, the use of GitHub Packages (ghcr.io/…) would be a nice alternative to have to DockerHub. When I’ve done this (https://github.com/KineticCafe/docker-aws-cli-session-manager/pkgs/container/aws-cli-session-manager and a couple of others in the KineticCafe organization), I have published them under the same names, but I’m wondering if it might not be better to publish these under different package names because I don't necessarily know that the tags would be any nicer to manage.

Given that Docker is introducing some level of consumption-based pricing (see https://www.docker.com/pricing/faq/#:~:text=What%20does%20Docker%20Hub%20Consumption%20Pricing%20mean%3F), this would not be a bad thing to have as an alternative.

I *believe* that it should be possible to migrate images (I haven't yet tried to do so, mostly because I started pushing to both ghcr and DockerHub at the same time) as [this post](https://friendlyuser.github.io/posts/docker_hub_to_github_packages/) suggests. Note that (1) it talks about *moving* images (I believe that existing images should be copied, not moved) and (2) it uses the old docker.pkg.github.com registry, not ghcr.io.

**Comment by ericmj** [comment]
The Docker FAQ seems to refer to private repository pulls. Are there any changes coming for public images?

**Comment by halostatue** [comment]
I'm not entirely sure, TBH. I know that all pulls are rate limited by IP regardless of authentication, but at different levels. Given that the post announcing the changes was a "we've made everything better" post that buried a fairly substantial price increase, I don't think the pull rate limits are going to get _better_.

If everyone switched to ghcr instead of DockerHub (which isn't happening for a bunch of reasons involving base images at a minimum) then GitHub might have to respond similarly, but I'm personally getting a real "pray I do not alter it any further" vibe from this latest Docker change.

**Comment by ericmj** [comment]
It's not really clear to me what the changes are or what the implications are (and it's of course an issue that Docker makes it so hard to understand). But until we know I would refrain from making any changes to Bob since supporting multiple registries would require extra maintenance. The way we build images unfortunately requires a lot of storage so we may also run into hidden GitHub limits.

**Comment by halostatue** [comment]
Understood; the images that I’m storing are much smaller and more constrained, so I don't expect my OSS use of them to be problematic, but I appreciate the immutable nature of the hexpm image tags.

**Comment by ericmj** [comment]
I will close the issue for now but if the docker changes turn out to be breaking we will of course reconsider. Thanks for raising the issue and for the proposal!

If other people are interested in GHCR images please drop a comment or thumbs down and we can reevaluate baed on that as well.

**Comment by halostatue** [comment]
If this changes, I would be happy to provide what assistance I can.
