### ISSUE TITLE
Support pre-build package for macOS?

### ISSUE THREAD

**Issue by niku** [hexpm/bob#36]
I've create a [PR](https://github.com/actions/setup-elixir/pull/17) that supports to working on macOS. `setup-elixir` on linux uses pre-build package that is built by bob. It takes about 10 seconds. On the other hand, on macOS builds from source code takes about 8-9 minutes. Using pre-build package is 500x faster than build from source code.

I wonder that if it could use bob built packages for macOS, it reduces setup time as like linux. Would you have plan to support for macOS?

**Comment by ericmj** [comment]
We would like to provide macOS builds, the problem is that we use Google Cloud that doesn't have mac machines. An alternative would be cross-compiling but it requires researching if it is possible and how to cross-compile Erlang from Linux to macOS.

**Comment by niku** [comment]
What do you think about using other environment such as github actions or travis ci and so on for building macOS binaries? I guess it can be start earlier. But it's difficult to fully control thus hard to solve a trouble when we needed.

**Comment by ericmj** [comment]
That is certainly possible, but it would no longer be Bob so it should be done outside of this project.

We have discussed using CI systems before but as you mention it removes control from us so we have opted out of it.

**Comment by niku** [comment]
It makes sense! Thank you for your quick response.
My question is solved. So I'm OK to close this issue. On the other hand, I think it might be useful for other people. If so, I leave it open.

May I close this issue?
