### ISSUE TITLE
Alpine images with OTP 19 can't install rebar

### ISSUE THREAD

**Issue by dbernheisel** [hexpm/bob#39]
Heyo,
Thanks for the great work here! I really appreciate it.

I ran into an issue when trying to use the Erlang 19 tags of the alpine docker images; I can't seem to get passed `mix local.rebar` due to an SSL issue. 

I have a small repo up with `mix new` here and the Github Actions setup to run a bunch CI tasks like running dialyzer, credo, mix format checks, and tests:

https://github.com/dbernheisel/hexbob-github-ci-sample
specifically: https://github.com/dbernheisel/hexbob-github-ci-sample/actions/runs/46820506

I have this setup for Alpine:

```bash
apk update
apk upgrade
apk add --no-cache make bash zlib openssl openssh git g++ wget curl ca-certificates
```

Here's the error I get:

```bash
Run mix local.rebar --force
** (MatchError) no match of right hand side value: {:error, {:ssl, {'no such file or directory', 'ssl.app'}}}
    (mix) lib/mix/utils.ex:432: Mix.Utils.read_httpc/1
    (mix) lib/mix/utils.ex:376: Mix.Utils.read_path/2
    (mix) lib/mix/local.ex:139: Mix.Local.read_path!/2
    (mix) lib/mix/local.ex:118: Mix.Local.find_matching_versions_from_signed_csv!/2
    (mix) lib/mix/tasks/local.rebar.ex:98: Mix.Tasks.Local.Rebar.install_from_s3/4
    (mix) lib/mix/tasks/local.rebar.ex:53: Mix.Tasks.Local.Rebar.run/1
    (mix) lib/mix/task.ex:300: Mix.Task.run_task/3
    (mix) lib/mix/cli.ex:58: Mix.CLI.run_task/2

##[error]Process completed with exit code 1.
```

![image](https://user-images.githubusercontent.com/643967/75564701-972a4200-5a1a-11ea-94e2-b5b6405003dc.png)

**Comment by ericmj** [comment]
It is possible older OTP versions does not work correctly on alpine. The official docker images do not build OTP 19 on alpine.

If you find a fix for this issue we can apply patch before building.

**Comment by ericmj** [comment]
OTP seems to build with the ssl application if the `libressl-dev` package is installed instead of `openssl-dev`. But it's likely then that that `libressl` package will be needed at runtime which isn't ideal either.

**Comment by ericmj** [comment]
We know install `openssl` and `libressl` respectively on the alpine images for the appropriate versions.

This fixes the reported issue and the SSL application now works correctly on alpine and OTP 19.
