### ISSUE TITLE
Consider installing Git on images

### ISSUE THREAD

**Issue by Shayon** [hexpm/bob#47]
If a project has a dependency that is linked through git compiling will fail with:
```
** (Mix) Error fetching/updating Git repository: the "git" executable is not available in your PATH. Please install Git on this machine or pass --no-deps-check if you want to run a previously built application on a system without Git.
```
I would ask that we consider pre-installing git on the base images so in scenarios like this we would not require consumers of the images to install it themselves.

**Comment by josevalim** [comment]
I think it is better if the images do one thing and one thing well. Extra deps can always be added on top. :)

**Comment by wojtekmach** [comment]
Yes, if we do that then someone else might have the opposite problem and want the smallest possible image. It's not feasible to add another 'variant' like full/minimal because we are already building a ton of combinations.

**Comment by Shayon** [comment]
Yeah, that's what I figured :smile: I thought since this was a dependency Mix itself used we might make and exception, but I can see why we'd take that stance. :+1:
