### ISSUE TITLE
No docker images for OTP 22.3.4.1

### ISSUE THREAD

**Issue by zoldar** [hexpm/bob#49]
👋 For some reason, there are no docker images published for OTP 22.3.4.1. At the same time, this version seems to be present in the builds list for `alpine` for instance: https://repo.hex.pm/builds/otp/alpine-3.10/builds.txt

**Comment by ericmj** [comment]
We don't build images for sub-patch versions since they are internal OTP releases.

**Comment by zoldar** [comment]
Ok, thanks for clarifying.

**Comment by ericmj** [comment]
After some clarification it turns out we should build those tags andI have started the builds for them. 22.3.4.1 is currently in the backlog, it will take a while until it is built.

**Comment by zoldar** [comment]
Sorry for bringing that up again, but just for the record, it seems that even though bob has finished publishing builds ~2 hous ago, 22.3.4.1 is still not there :(

**Comment by ericmj** [comment]
No, we are still processing the backlog. There's quite a few erlang and elixir images that needs to be built so it's going to take a while.
