### ISSUE TITLE
/builds/elixir/builds.txt should be ordered

### ISSUE THREAD

**Issue by wojtekmach** [hexpm/bob#52]
Currently we use natural ordering:

```
$ curl https://repo.hex.pm/builds/elixir/builds.txt
(...)
v1.1.1-otp-18 139d2eac5998259379862ff6ed2a5287f7de4ea6 2020-03-25T22:13:44Z bdfa8f86fc0ca296c045b67d6c7d9a7b25f3dddcb2388c066dddfe03e231a0aa
v1.10 1145dc01680aab7094f8a6dbd38b65185e14adb4 2020-07-04T11:27:55Z 0ff70d25a8332cc8aeb8da75de28f9ff36f0b124c16320255db6213e7fadc2dc 32a996366fb543d65a526bb5b4be8e2b09c57f5b9013e3ff7af50bf6d628742f
v1.2 9c91d2cc91fa2ee2ceb88075e69e5eb18bbb1af8 2020-03-25T22:16:42Z 9bc461faad6f92f10f09e5d3b61b216dc4b28122cdae3a28b3bbfac8a693160f
(...)
```

we should use semver based ordering instead.

**Comment by ericmj** [comment]
I think this is fine. Is there a reason to order it?

It's hard for us to use semver ordering since we are in bash land when writing this file. If there is an easy fix we could do it but otherwise I would wait until this is moved to the elixir team and fix it then.

**Comment by wojtekmach** [comment]
I think it would be more convenient to see the latest versions at the bottom. But yeah, there doesn't seem to be an easy fix for it (unless we e.g. shell out to Elixir) so I agree it is fine to keep things as is for now.
