### ISSUE TITLE
Elixir 1.10.4 & OTP 23 not building

### ISSUE THREAD

**Issue by samhamilton** [hexpm/bob#53]
Hey, 

I just spotted that the new 1.10.4 image for OTP 23 has not been pushed to Docker hub?

- https://hub.docker.com/r/hexpm/elixir/tags?page=1&name=1.10.4-erlang-22 - pushed
- https://hub.docker.com/r/hexpm/elixir/tags?page=1&name=1.10.4-erlang-23 - no image found

Thanks
Sam

**Comment by ericmj** [comment]
This has been fixed, thanks for the report.

**Comment by samhamilton** [comment]
Thanks! @ericmj
