### ISSUE TITLE
Add support for debian bullseye docker image

### ISSUE THREAD

**Issue by wingyplus** [hexpm/bob#59]
Currently, I see elixir tag support only buster as a latest release on debian. But bullseye which's latest release of debian is missing. 

Ref: https://hub.docker.com/_/debian.

**Comment by wingyplus** [comment]
After I read https://github.com/hexpm/bob/blob/master/lib/bob/job/docker_checker.ex. Do we needs to bump Erlang to bullseye together with Elixir?

**Comment by ericmj** [comment]
It looks like bullseye is not released yet? [1] We only plan to support stable releases of packages and operating systems.

[1] https://en.wikipedia.org/wiki/Debian_version_history#Release_table

**Comment by wingyplus** [comment]
@ericmj yes, it’s currently in testing stage. If that so, it would be out of scope right?

**Comment by ericmj** [comment]
Yes, we only build on released software.
