### ISSUE TITLE
Docs missing

### ISSUE THREAD

**Issue by princemaple** [hexpm/bob#69]
Hi thanks for pushing towards building docs into the images.

However I'm still not getting the docs for some reason. I use this tag: `1.11.2-erlang-23.1-alpine-3.12.0`

**Comment by princemaple** [comment]
I tried the tag `1.11.1-erlang-23.1.4-ubuntu-groovy-20201022.1` in this tweet https://twitter.com/wojtekmach/status/1331153683279716352

The docs are there.

**Comment by ericmj** [comment]
We didn't rebuild images using old OS versions to include docs, you need to use alpine 3.12.1 `1.11.2-erlang-23.1-alpine-3.12.1`.

**Comment by princemaple** [comment]
Great. Got it.

**Comment by princemaple** [comment]
Thanks!
