### ISSUE TITLE
Access denied for Elixir 1.6.4

### ISSUE THREAD

**Issue by fkumro** [hexpm/bob#7]
When attempting to retrieve Elixir 1.6.4 (via asdf elixir plugin), the following error is returned:

```xml
<Error>
<Code>AccessDenied</Code>
<Message>Access Denied</Message>
<RequestId>D402D51C8E04D764</RequestId>
<HostId>woNgufQ2OUZI1U0DzWVP6QdWaWm2qBjc+/nAyAMXlP99HhtIb+IjZZetIT57Z7Sr5ZVmAwJW/hs=</HostId>
</Error>
```

URL: https://repo.hex.pm/builds/elixir/v1.6.4.zip

**Comment by cehoffman** [comment]
Similar for the otp specific builds, e.g. http://repo.hex.pm/builds/elixir/v1.6.4-otp-20.zip

**Comment by ericmj** [comment]
The builds are now available. An earlier build was stuck and was blocking the build queue.
