### ISSUE TITLE
Have Erlang/OTP 17-19 work with Ubuntu 18.04

### ISSUE THREAD

**Issue by paulo-ferraz-oliveira** [hexpm/bob#82]
As per @wojtekmach's https://github.com/erlef/setup-beam/issues/7 and @ericmj's https://github.com/erlef/setup-beam/issues/7#issuecomment-797451084 Erlang/OTP should work (there's an SSL-related issue) with Ubuntu 18.04.

~I'm not sure this would solve https://github.com/hexpm/bob/issues/70, but potentially.~

**Comment by ericmj** [comment]
https://github.com/hexpm/bob/issues/70 is not related since it's about docker containers.

**Comment by ericmj** [comment]
This issue should be on the setup-beam repo. The build is likely correct, what we need to explore is if we can change the installed Ubuntu packages in the action.

**Comment by ericmj** [comment]
I can't transfer between organizations.

We need to look into if changing the version the ssl libraries will fix the issue. The order this is done does not matter.

**Comment by paulo-ferraz-oliveira** [comment]
Closing as per the mention.
